.PHONY: all
CC :=gcc

all:
	$(CC) bai1.c -o bai1
	$(CC) bai2.c -o bai2
	$(CC) bai3.c -o bai3
	$(CC) bai4.c -o bai4
	$(CC) bai5.c -o bai5
	$(CC) bai6.c -o bai6
	$(CC) bai7.c -o bai7
	$(CC) bai8.c -o bai8
	$(CC) bai9.c -o bai9
	$(CC) bai10.c -o bai10
	$(CC) bai11.c -o bai11
	$(CC) bai12.c -o bai12
	$(CC) bai13.c -o bai13
	$(CC) bai14.c -o bai14
	$(CC) bai15.c -o bai15
	$(CC) bai16.c -o bai16
	$(CC) bai17.c -o bai17
clean:
	rm -rf *o bai1
	rm -rf *o bai2
	rm -rf *o bai3
	rm -rf *o bai4
	rm -rf *o bai5
	rm -rf *o bai6
	rm -rf *o bai7
	rm -rf *o bai8
	rm -rf *o bai9
	rm -rf *o bai10
	rm -rf *o bai11
	rm -rf *o bai12
	rm -rf *o bai13
	rm -rf *o bai14
	rm -rf *o bai15
	rm -rf *o bai16
	rm -rf *o bai17