.PHONY: all
CC :=gcc
all:
	$(CC) bai1.c -o bai1
	$(CC) bai2.c -o bai2
	$(CC) bai4.c -o bai4
	$(CC) bai5.c -o bai5
	$(CC) bai6.c -o bai6
clean:
	rm -rf *o bai1
	rm -rf *o bai2
	rm -rf *o bai4
	rm -rf *o bai5
	rm -rf *o bai6
	