.PHONY : all
CC := gcc
CFLAGS := -I.
 all:
	$(CC) bai1.c -o bai1
	$(CC) bai2.c -o bai2
	$(CC) bai3.c -o bai3
	$(CC) bai4.c -o bai4
	$(CC) bai5.c -o bai5
	$(CC) bai6.c -o bai6
	$(CC) bai7.c -o bai7
	$(CC) bai8.c -o bai8
	$(CC) bai8.1.c -o bai8.1
	$(CC) bai9.c -o bai9
clean:
	rm -rf *o bai1
	rm -rf *o bai2
	rm -rf *o bai3
	rm -rf *o bai4
	rm -rf *o bai5
	rm -rf *o bai6
	rm -rf *o bai7
	rm -rf *o bai8
	rm -rf *o bai8.1
	rm -rf *o bai9